//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSPAssemblyHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("562.5")]
        public double UnitMass_Small_Wet {
            get {
                return ((double)(this["UnitMass_Small_Wet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4500")]
        public double UnitMass_Large_Wet {
            get {
                return ((double)(this["UnitMass_Large_Wet"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62.5")]
        public double UnitMass_Small_Dry {
            get {
                return ((double)(this["UnitMass_Small_Dry"]));
            }
            set {
                this["UnitMass_Small_Dry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double UnitMass_Large_Dry {
            get {
                return ((double)(this["UnitMass_Large_Dry"]));
            }
            set {
                this["UnitMass_Large_Dry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78.675")]
        public double UnitMass_Tiny_Wet {
            get {
                return ((double)(this["UnitMass_Tiny_Wet"]));
            }
            set {
                this["UnitMass_Tiny_Wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double UnitMass_Tiny_Dry {
            get {
                return ((double)(this["UnitMass_Tiny_Dry"]));
            }
            set {
                this["UnitMass_Tiny_Dry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20500")]
        public double UnitMass_Extra_Wet {
            get {
                return ((double)(this["UnitMass_Extra_Wet"]));
            }
            set {
                this["UnitMass_Extra_Wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public double UnitMass_Extra_Dry {
            get {
                return ((double)(this["UnitMass_Extra_Dry"]));
            }
            set {
                this["UnitMass_Extra_Dry"] = value;
            }
        }
    }
}
